Repository ynput/ayon-react-components, pull requests merged in 2024-05, with the labels that each got.

#80 79 dialog implementation fixes
  src/Dropdowns/Dropdown/Dropdown.stories.tsx
  src/Dropdowns/Dropdown/Dropdown.tsx
  src/Overlay/Dialog/Dialog.stories.tsx
  src/Overlay/Dialog/Dialog.styled.ts
  src/Overlay/Dialog/Dialog.tsx
Labels: bug

#83 79 dialog implementation fixes
  src/Overlay/Dialog/Dialog.stories.tsx
  src/Overlay/Dialog/Dialog.styled.ts
  src/Overlay/Dialog/Dialog.tsx
Labels: bug

#89 fix: hide close button by default
  src/Overlay/Dialog/Dialog.stories.tsx
  src/Overlay/Dialog/Dialog.styled.ts
  src/Overlay/Dialog/Dialog.tsx
Labels: bug, HIGH

#91 Dropdown: re-rendering bug and fixes
  src/Dropdowns/Dropdown/Dropdown.stories.tsx
  src/Dropdowns/Dropdown/Dropdown.tsx
Labels: bug

#95 fix: added z-index for backdrop in Dialog
  src/Overlay/Dialog/Dialog.styled.ts
Labels: bug

#97 chore(icon): upgrade to 0.17.4 with new icons
  package.json
  src/Icon/icons.json
  src/Icon/index.tsx
Labels: maintenance

#100 enhancement: disableReorder prop replaced with sortbySelected (defau…
  src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
  src/Dropdowns/Dropdown/Dropdown.stories.tsx
  src/Dropdowns/Dropdown/Dropdown.tsx
  src/Dropdowns/TagsSelect/TagsSelect.tsx
  src/Dropdowns/VersionSelect/VersionSelect.tsx
Labels: enhancement

#101 Add issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: maintenance

#102 enhancement: added no backdrop option for dialog
  src/Overlay/Dialog/Dialog.stories.tsx
  src/Overlay/Dialog/Dialog.tsx
Labels: enhancement

#104 chore(dialog): better scroll story
  src/Overlay/Dialog/Dialog.stories.tsx
Labels: bug

#109 Release 1.0.13
  src/Dropdowns/Dropdown/DefaultValueTemplate.tsx
  src/Dropdowns/Dropdown/Dropdown.stories.tsx
  src/Dropdowns/Dropdown/Dropdown.tsx
Labels: enhancement

#112 Assignee Select: setting first assignee closes dropdown automatically
  src/Dropdowns/AssigneeSelect/AssigneeField.tsx
  src/Dropdowns/AssigneeSelect/AssigneeSelect.stories.tsx
  src/Dropdowns/AssigneeSelect/AssigneeSelect.tsx
Labels: enhancement
