Repository ynput/ayon-react-components, pull requests merged in 2024-04, with the labels that each got.

#66 Dropdown search and adding
  src/Dropdowns/Dropdown/Dropdown.tsx
Labels: bug, enhancement

#64 Enhancement/ay 4612 dialog component
  src/Inputs/InputColor/InputColor.tsx
  src/Inputs/LockedInput/LockedInput.stories.tsx
  src/Overlay/Dialog/Dialog.stories.tsx
  src/Overlay/Dialog/Dialog.styled.ts
  src/Overlay/Dialog/Dialog.tsx
Labels: enhancement

#70 Fix: entity card image not showing
  src/EntityCard/EntityCard.styled.ts
  src/EntityCard/EntityCard.tsx
Labels: bug

#72 enhancement: added switch for showing/hiding characters in password + textinput
  src/Inputs/InputNumber/InputNumber.tsx
  src/Inputs/InputPassword/InputPassword.stories.tsx
  src/Inputs/InputPassword/InputPassword.tsx
  src/Inputs/InputText/InputText.tsx
  src/Inputs/styles.tsx
Labels: enhancement
